---
- name: Prepare RHEL 7 hosts for LEAPP
  hosts: all
  tasks:
    # stop and disable puppet
    - name: Stop and disable puppet
      ansible.builtin.service:
        name: puppet
        state: stopped
        enabled: false
      when: ansible_distribution_major_version == "7"
