---
- name: Prepare RHEL 7 hosts for LEAPP
  hosts: all
  tasks:
    # stop and disable puppet
    - name: Stop and disable puppet
      ansible.builtin.service:
        name: puppet
        state: stopped
        enabled: false
      when: ansible_distribution_major_version == "7"
    # install the cockpit and cockpit-leapp packages
    - name: Install the cockpit and cockpit-leapp packages
      ansible.builtin.package:
        name:
          - cockpit
          - cockpit-leapp
        state: present
      when: ansible_distribution_major_version == "7"
    # open the firewall for the cockpit service
    - name: Open the firewall for the cockpit service
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        state: enabled
      when: ansible_distribution_major_version == "7"
